

services:
  mdbnavigator-api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTPS_PORTS=3001
        - ASPNETCORE_HTTPS_PORT=3002
        - ASPNETCORE_Kestrel__Certificates__Default__Password=123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/mdbnavigator.pfx
    container_name: mdbnavigator-api
    image: kalliman/mdbnavigator-api
    build:
      context: .
      dockerfile: MDBNavigator.API/Dockerfile
    ports:
        - "3001:3001"
        - "3002:3002"
    volumes:
        - ~/.aspnet/https:/https:ro
        - /https/mdbnavigator.pfx:/https/mdbnavigator.pfx

  mdbnavigator-ui:
    build:
      context: mdb-navigator-ui
      dockerfile: Dockerfile
    image: kalliman/mdbnavigator-ui
    container_name: mdbnavigator-ui
    ports :
      - "3000:3000"
    depends_on:
      - mdbnavigator-api
    