services:
  mdbnavigator.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Release
        - ASPNETCORE_HTTPS_PORTS=3001
        - ASPNETCORE_HTTPS_PORT=3002
        - ASPNETCORE_Kestrel__Certificates__Default__Password=123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/mdbnavigator.pfx
    container_name: mdbnavigator.api
    image: mdbnavigator.api
    build:
      context: .
      dockerfile: MDBNavigator.API/Dockerfile
    ports:
        - "3001:3001"
        - "3002:3002"
    volumes:
        - ~/.aspnet/https:/https:ro

  mdbnavigator.ui:
    build:
      context: mdb-navigator-ui
      dockerfile: Dockerfile
    image: mdbnavigator.ui
    container_name: mdbnavigator.ui
    ports :
      - "3000:3000"
    depends_on:
      - mdbnavigator.api
    